apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: zig
      containers:
        - name: code-server
          image: codercom/code-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server-secret
                  key: password
          volumeMounts:
            - name: code-data
              mountPath: /home/coder/project
      volumes:
        - name: code-data
          emptyDir: {}
