apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-data
  labels:
    app: code-server
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi