apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: homelab-realm
  namespace: keycloak
  labels:
    app: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    id: homelab
    realm: homelab
    displayName: Homelab Realm
    enabled: true
    loginWithEmailAllowed: true
    registrationAllowed: false
    resetPasswordAllowed: true
