apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloak
      version: "21.4.4" 
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      adminUser: admin
      existingSecret: keycloak-admin-secret
      passwordSecretKey: admin-password

    postgresql:
      enabled: true
      auth:
        existingSecret: keycloak-postgres-secret
        database: keycloak

    service:
      type: ClusterIP
      ports:
        http: 8080

    resources:
      limits:
        memory: 2Gi
        cpu: 2000m
      requests:
        memory: 1250Mi
        cpu: 1000m

    # Enable health endpoints for Keycloak 26.x
    extraEnvVars:
      - name: KC_HEALTH_ENABLED
        value: "true"
      - name: KC_METRICS_ENABLED
        value: "true"

    # Configure health probes with proper timing
    livenessProbe:
      enabled: true
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 1

    readinessProbe:
      enabled: true
      initialDelaySeconds: 120
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

    startupProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 15
      successThreshold: 1
