apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloak
      version: "^21.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      adminUser: admin
      existingSecret: keycloak-admin-secret
      passwordSecretKey: admin-password

    postgresql:
      enabled: true
      auth:
        existingSecret: keycloak-postgres-secret
        secretKeys:
          adminPasswordKey: postgres-password
        database: keycloak

    service:
      type: ClusterIP
      ports:
        http: 8080

    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m
