apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  labels:
    app: keycloak
stringData:
  username: keycloak
  password: super-change-me
  database: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
  labels:
    app: keycloak
stringData:
  username: admin
  password: admin-change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls
  namespace: keycloak
  labels:
    app: keycloak
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDIzCCAgugAwIBAgIUUApwIPgR02BZGESjAq8l0uRJCXswDQYJKoZIhvcNAQEL
    BQAwITEfMB0GA1UEAwwWa2V5Y2xvYWsuYmxhc2NvbGFiLmNvbTAeFw0yNTEyMTMw
    MTAyNDNaFw0yNjEyMTMwMTAyNDNaMCExHzAdBgNVBAMMFmtleWNsb2FrLmJsYXNj
    b2xhYi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCxsrVriB+8
    ieGidXBr/k+JEGL1WYo74oi+q+ivyG7gq8yBT80GWYKby3twelSN0v6m50wJzKfu
    kBQw8bXaIJQjeJBUcqqYPnTenM1vwnx26UDHhszr3JFkOqDzhxSYloD+bjvSABHV
    +z8Ig9Kb13nmt3IzrAswYMv/hoAVEiwiKgAMolhI+2avHl5TkCa8hMk+KJ0ZgNWX
    tfJeucZ0IXpnL+ZFVUUZeYz6OMNJa/VWbBD73o4UtGG8bg/nT89a1U4F6eilfXI3
    Yw8z4DRSJQ0puOj1vNbk3DdJBS38REGl1Igr9/t5+BbHFtH7wXVaFOUMXxdI4R+M
    KnPa4LoqCiRhAgMBAAGjUzBRMB0GA1UdDgQWBBR8Eyv/LQBW3vjxYWH+tfdQRelq
    ODAfBgNVHSMEGDAWgBR8Eyv/LQBW3vjxYWH+tfdQRelqODAPBgNVHRMBAf8EBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAYIpm53PyaLjDKcYs90nuVZIZgAVOp0pDn
    LS67yRb/dH/rsTCa3wCVopWF0aXlQTeLybEXMqjNK9XbM3f03wL1uzWb+jXoga9Q
    7kdVGWmmww1LqkbEGr2bFTlxU0NtgnbgVDq73WiX+ZQZZ7K9fxuB6eUTblYf76jL
    bD0SWkQ2uGPhJy06D2j/9GGl9JtnqUvYE/XIbKTyDbpCGuZM3ETlA6kEsH/kzb69
    iE6n0KMVsY23RPH4SXvszRzFP248Tz2h+XLFkEtWGpB/a64ng2Hp/BteDVhIRhRj
    99gFTD5HhqEMDHBG5DPt7FhcH4rD0FI3oy9mSMxFjrXhA5UTskxH
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCxsrVriB+8ieGi
    dXBr/k+JEGL1WYo74oi+q+ivyG7gq8yBT80GWYKby3twelSN0v6m50wJzKfukBQw
    8bXaIJQjeJBUcqqYPnTenM1vwnx26UDHhszr3JFkOqDzhxSYloD+bjvSABHV+z8I
    g9Kb13nmt3IzrAswYMv/hoAVEiwiKgAMolhI+2avHl5TkCa8hMk+KJ0ZgNWXtfJe
    ucZ0IXpnL+ZFVUUZeYz6OMNJa/VWbBD73o4UtGG8bg/nT89a1U4F6eilfXI3Yw8z
    4DRSJQ0puOj1vNbk3DdJBS38REGl1Igr9/t5+BbHFtH7wXVaFOUMXxdI4R+MKnPa
    4LoqCiRhAgMBAAECggEAKpXjeIPE51A77M0sRhVKRlTRAm+U+0kM8HUObKIiQGGr
    vwm63tywulmHmasXfG2mbaVcybRsQnXxANHMfRv1pJKONE7Op3HAXGFDspbvcSfx
    SF/72EKh7V1HmVU0EGVxQIh2eZtequNtdcLxxDtdkXdBPTTr8YohGXnIVERooz76
    B7YQL52tqtUE5cnIRpssFIBSOP4VXE2F4WUHNDtcDKeOe1bCzA9GSggkWVbq8KM9
    JtaXp8K/Vm6BRb3EI6RIYswQTm5jChptDsXr3rYc8l0nB7LBMHD4Knp1jmoQXxXS
    O7wAqo61ZvO84fR2ekG0Xjt443u9dx2Cv5DpuNGm6QKBgQD5rygvqEgeh8/SFg4c
    Sm1M2t5Qd10iPOCd3nYNbVfunhK3BzYWjzMvcLgS9hSdqOm+GB9dUyHxXJsLnL24
    +ascN6AJ4pB5Bfy5kJwsPCwkgFWx8i4k/Fj87f1H6Dbu36Jfz2uJ3zDUXNMHVtwj
    NbSar4zepSLYe1C44iCJIfxBrwKBgQC2MWbcnLFexNi9SeJvXalB6RpE6yf/d5qV
    bF1FR41lcu28Be73NMyR3q1HK2tajcE18MINFkpP4vCncf+fPWWW6QuF2xpTxxIM
    EymEouXowG713gHBRoaLDBDc511wWvmC/nbKn5SiQv89Eldgs75cbGf2ewypqfO/
    IHY8abLO7wKBgBxPjwfwVdUYYykYFRuCGOiY/JI1JptGOdXMrqgRGOJWjBqyt6BR
    NmWPq1+DBY1m5LIIPC4xyex7Kp1jdWOu84bsi7nzNZxzYFeOHRcq73poDs9xfWf2
    MQTk204291uYgenJNBFa/EdoCwmPAMEBSuwrMZbhNJVFTj7YbQX/k4HDAoGAQ9we
    rekG/39eIxLT7hr6ofwKtsTHvxVzVFhqXRWLis/F0JR9L0JRN7uy2qFHeRD3d/nW
    rT0yLJMgg52oUk1x+0WN7ytuoOmyxSCWBDsQWyLhsV4hVTXJgxzZYw4h9WlNKgdR
    g6Lwn4dIvhyIwxHvw0j1aA7o5oDQss2KfHH6Ea0CgYA4sIF5/DyxxPdXh7s/ZOXF
    v97RQDIB0gb9wuEHYEA0ZXYqxi08FBhQZLxQqZPmv42zRfGcxUCIjIAoNhEj/4pl
    14NpHmX/G5xGMAloaHwcCxbg4bwKrN8/0nx1Dt2f0JqFwFH3+Raw2NAIxK1h+Nig
    trsJ0SvKZEHtmllW/PV2BA==
    -----END PRIVATE KEY-----
