apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  labels:
    app: keycloak
stringData:
  username: keycloak
  password: super-change-me
  database: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
  labels:
    app: keycloak
stringData:
  username: admin
  password: admin-change-me
