apiVersion: v1
kind: Service
metadata:
  name: dashy-auth
  namespace: dashy
  labels:
    app: dashy
    component: auth
spec:
  selector:
    app: dashy-oauth2-proxy
  ports:
    - name: http
      port: 80
      targetPort: 4180
  type: ClusterIP
