apiVersion: v1
kind: Secret
metadata:
  name: dashy-oauth2-secret
  namespace: dashy
  labels:
    app: dashy
    component: auth
stringData:
  client_id: dashy-client
  client_secret: change-me-super-secret
  cookie_secret: DpY++sU2lJleE6W4k9m8Rg==
