apiVersion: batch/v1
kind: Job
metadata:
  name: affine-migration
  namespace: affine
spec:
  template:
    spec:
      containers:
        - name: affine-migration-job
          image: ghcr.io/toeverything/affine:stable
          command:
            - sh
            - -c
            - node ./scripts/self-host-predeploy.js
          envFrom:
            - configMapRef:
                name: affine-env
          volumeMounts:
            - name: affine-storage
              mountPath: /root/.affine/storage
            - name: affine-config
              mountPath: /root/.affine/config
      restartPolicy: OnFailure
      volumes:
        - name: affine-storage
          persistentVolumeClaim:
            claimName: affine-claim-storage
        - name: affine-config
          persistentVolumeClaim:
            claimName: affine-claim-config
