apiVersion: apps/v1
kind: Deployment
metadata:
  name: affine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affine
  template:
    metadata:
      labels:
        app: affine
    spec:
      containers:
        - name: affine-server
          image: ghcr.io/toeverything/affine:stable
          ports:
            - containerPort: 3010
              protocol: TCP
          env:
            - name: AFFINE_INDEXER_ENABLED
              value: "false"
            - name: DB_PASSWORD
              value: "change-me"  # Hardcoded password (no secret management)
            - name: DATABASE_URL
              value: postgresql://affine:change-me@postgres:5432/affine
            - name: REDIS_SERVER_HOST
              value: redis
          envFrom:
            - configMapRef:
                name: env
          volumeMounts:
            - name: affine-claim0
              mountPath: /root/.affine/storage
            - name: affine-claim1
              mountPath: /root/.affine/config
      restartPolicy: Always
      volumes:
        - name: affine-claim0
          persistentVolumeClaim:
            claimName: affine-claim0
        - name: affine-claim1
          persistentVolumeClaim:
            claimName: affine-claim1
