apiVersion: apps/v1
kind: Deployment
metadata:
  name: affine
  namespace: affine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affine
  template:
    metadata:
      labels:
        app: affine
    spec:
      containers:
        - name: affine-server
          image: ghcr.io/toeverything/affine:stable
          ports:
            - containerPort: 3010
          envFrom:
            - configMapRef:
                name: affine-env
          volumeMounts:
            - name: affine-storage
              mountPath: /root/.affine/storage
            - name: affine-config
              mountPath: /root/.affine/config
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "npx prisma migrate deploy"
      restartPolicy: Always
      volumes:
        - name: affine-storage
          persistentVolumeClaim:
            claimName: affine-claim-storage
        - name: affine-config
          persistentVolumeClaim:
            claimName: affine-claim-config
