apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: affine
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - storage.yaml
  - postgres.yaml
  - redis.yaml
  - secret.yaml  # You can keep this if you want to have the basic secret for DB password
  - prisma-migration.yaml
