apiVersion: batch/v1
kind: Job
metadata:
  name: affine-migrate
  namespace: affine
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure

      # Wait until Postgres is accepting connections
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command: ["/bin/sh","-lc"]
          args:
            - >
              until pg_isready -h postgres -p 5432 -d affine -U affine; do
                echo "Waiting for postgres...";
                sleep 2;
              done
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: affine-db-secret
                  key: password

      containers:
        - name: migrate
          image: ghcr.io/toeverything/affine:stable
          workingDir: /app
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: affine-db-secret
                  key: password
            - name: DATABASE_URL
              value: postgresql://affine:$(DB_PASSWORD)@postgres:5432/affine
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -e
              cd /app
              echo "Probing for Prisma CLI..."
              ls -l node_modules/.bin || true
              if [ -x node_modules/.bin/prisma ]; then
                echo "Using local prisma binary"
                node_modules/.bin/prisma migrate deploy --schema=/app/prisma/schema.prisma
              elif command -v npx >/dev/null 2>&1; then
                echo "Using npx prisma"
                npx --yes prisma@latest migrate deploy --schema=/app/prisma/schema.prisma
              elif command -v yarn >/dev/null 2>&1; then
                echo "Using yarn prisma"
                yarn prisma migrate deploy --schema=/app/prisma/schema.prisma
              else
                echo "Falling back to prisma JS entrypoint"
                node node_modules/prisma/build/index.js migrate deploy --schema=/app/prisma/schema.prisma
              fi
