apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migration
  namespace: affine
spec:
  template:
    spec:
      containers:
        - name: prisma-migration
          image: ghcr.io/toeverything/affine:stable
          command:
            - sh
            - -c
            - |
              echo "Running Prisma Migrations..."
              npx prisma migrate deploy
          envFrom:
            - configMapRef:
                name: affine-env
          volumeMounts:
            - name: affine-storage
              mountPath: /root/.affine/storage
            - name: affine-config
              mountPath: /root/.affine/config
      restartPolicy: OnFailure
      volumes:
        - name: affine-storage
          persistentVolumeClaim:
            claimName: affine-claim-storage
        - name: affine-config
          persistentVolumeClaim:
            claimName: affine-claim-config
