apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-mirror-script
  namespace: lakehouse
data:
  mirror.sh: |
    #!/usr/bin/env sh
    set -eu
    set -x

    SRC_ROOT="/mnt/datalake/landing/homeassistant"
    DST_BUCKET="landing"
    DST_PREFIX="homeassistant"

    echo "[*] Listing source:"
    ls -lah "${SRC_ROOT}" || true
    find "${SRC_ROOT}" -maxdepth 4 -type f | head -30 || true

    # ---- ensure mc exists (works on Alpine-based images) ----
    if ! command -v mc >/dev/null 2>&1; then
      echo "[*] Installing mc..."
      # Try Alpine first; fall back to curl-only
      if command -v apk >/dev/null 2>&1; then
        apk add --no-cache ca-certificates curl >/dev/null 2>&1 || true
      fi
      curl -fsSL https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc
      chmod +x /usr/local/bin/mc
    fi
    mc --version || true
    # ---------------------------------------------------------

    echo "[*] Configure alias..."
    mc alias set minio http://minio.lakehouse.svc.cluster.local:9000 \
      "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}" --api S3v4

    echo "[*] List buckets:"
    mc ls minio || true

    # If source missing/empty, exit 0 so CronJob doesn’t crashloop
    if [ ! -d "${SRC_ROOT}" ] || [ -z "$(ls -A "${SRC_ROOT}" 2>/dev/null || true)" ]; then
      echo "[!] Source empty/missing: ${SRC_ROOT}. Nothing to mirror."
      exit 0
    fi

    mc mb minio/${DST_BUCKET} || true

    echo "[*] Mirroring ${SRC_ROOT} -> minio/${DST_BUCKET}/${DST_PREFIX}"
    # Safe while validating (no delete). Re-add --remove later if you want parity deletes.
    mc mirror --overwrite "${SRC_ROOT}" "minio/${DST_BUCKET}/${DST_PREFIX}"

    echo "[*] Verify a few objects exist:"
    mc ls -r "minio/${DST_BUCKET}/${DST_PREFIX}" | head -50 || true

    OBJ="$(mc ls -r "minio/${DST_BUCKET}/${DST_PREFIX}" | awk '$6 !~ /\/$/ {print $6; exit}' || true)"
    if [ -n "${OBJ}" ]; then
      echo "[✓] Found object: ${OBJ}"
      mc stat "minio/${DST_BUCKET}/${DST_PREFIX}/${OBJ}" || true
      echo "[✓] Mirror OK."
      exit 0
    else
      echo "[x] Mirror finished but no files found under ${DST_BUCKET}/${DST_PREFIX}."
      exit 2
    fi
