apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-mirror-script
  namespace: lakehouse
data:
  mirror.sh: |
    #!/usr/bin/env sh
    set -eu
    set -x
    export PATH="$PATH:/opt/bitnami/minio-client/bin:/opt/bitnami/common/bin"

    MC="mc"
    if ! command -v "$MC" >/dev/null 2>&1; then
      if command -v mcli >/dev/null 2>&1; then MC="mcli"; fi
    fi

    SRC_ROOT="/mnt/datalake/landing/homeassistant"
    DST_BUCKET="landing"
    DST_PREFIX="homeassistant"

    echo "[*] Listing source:"
    ls -lah "${SRC_ROOT}" || true
    find "${SRC_ROOT}" -maxdepth 4 -type f | head -30 || true

    echo "[*] $MC version:"; "$MC" --version || true

    echo "[*] Configure alias..."
    "$MC" alias set minio http://minio.lakehouse.svc.cluster.local:9000 \
      "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}" --api S3v4

    echo "[*] List buckets:"; "$MC" ls minio || true

    if [ ! -d "${SRC_ROOT}" ] || [ -z "$(ls -A "${SRC_ROOT}" 2>/dev/null || true)" ]; then
      echo "[!] Source empty/missing: ${SRC_ROOT}. Nothing to mirror."; exit 0
    fi

    "$MC" mb "minio/${DST_BUCKET}" || true

    echo "[*] Mirroring ${SRC_ROOT} -> minio/${DST_BUCKET}/${DST_PREFIX}"
    "$MC" mirror --overwrite \
      --exclude "*/.cache/*" \
      --exclude "*/.git/*" \
      --exclude "*/.DS_Store" \
      "${SRC_ROOT}" "minio/${DST_BUCKET}/${DST_PREFIX}"

    echo "[*] Verify:"
    "$MC" ls -r "minio/${DST_BUCKET}/${DST_PREFIX}" | head -50 || true
    OBJ="$("$MC" ls -r "minio/${DST_BUCKET}/${DST_PREFIX}" | awk '$6 !~ /\/$/ {print $6; exit}' || true)"
    if [ -n "${OBJ:-}" ]; then
      echo "[✓] Found object: ${OBJ}"
      "$MC" stat "minio/${DST_BUCKET}/${DST_PREFIX}/${OBJ}" || true
      echo "[✓] Mirror OK."; exit 0
    else
      echo "[x] Mirror finished but no files found under ${DST_BUCKET}/${DST_PREFIX}."; exit 2
    fi
