apiVersion: batch/v1
kind: CronJob
metadata:
  name: ha-landing-to-minio
  namespace: lakehouse
spec:
  schedule: "15 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          restartPolicy: OnFailure
          containers:
            - name: mc
              image: bitnami/minio-client:latest
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh","-lc","/script/mirror.sh"]
              envFrom:
                - secretRef:
                    name: minio-creds
              volumeMounts:
                - name: datalake
                  mountPath: /mnt/datalake
                  readOnly: true
                - name: script
                  mountPath: /script
          volumes:
            - name: datalake
              hostPath:
                path: /mnt/datalake
                type: Directory
            - name: script
              configMap:
                name: ha-mirror-script
                defaultMode: 0755
