# IMPORTANT: This file contains sensitive credentials and should be encrypted with SOPS before committing
# To encrypt this file, run: sops -e -i apps/staging/keycloak/secret.yaml
# The SOPS configuration in clusters/staging/.sops.yaml will automatically encrypt the stringData section
#
# After encryption, the file will contain encrypted values that are safe to commit to Git
# To edit encrypted values, run: sops apps/staging/keycloak/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
stringData:
  # PostgreSQL database password - replace with a strong random password
  DB_PASSWORD: "CHANGE_ME_db_password_min_32_chars_random"
  
  # Keycloak admin username
  KEYCLOAK_ADMIN: "admin"
  
  # Keycloak admin password - replace with a strong random password
  KEYCLOAK_ADMIN_PASSWORD: "CHANGE_ME_admin_password_min_32_chars_random"
