apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
        - name: nessie
          image: projectnessie/nessie:0.76.6
          ports:
            - containerPort: 19120
          env:
            - name: QUARKUS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: nessie-secret
                  key: AWS_ACCESS_KEY_ID
            - name: QUARKUS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: nessie-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: QUARKUS_NESSIE_VERSION_STORE_TYPE
              value: "rocks"
            - name: QUARKUS_HTTP_PORT
              value: "19120"
