apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  #storageClassName: sata # Used for spot.rackspace.com
