apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lakehouse
  name: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-operator
  template:
    metadata:
      labels:
        app: spark-operator
    spec:
      serviceAccountName: spark
      containers:
        - name: spark-operator
          image: ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.8-3.1.1
          args:
            - --namespace
            - lakehouse
          ports:
            - containerPort: 8080
              name: metrics
