apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-operator
  template:
    metadata:
      labels:
        app: spark-operator
    spec:
      serviceAccountName: spark
      containers:
        - name: spark-operator
          image: gcr.io/spark-operator/spark-operator:v1beta2-1.3.8-3.1.1
          args:
            - --install-crds=true
            - --enable-webhook=true
            - --namespace=lakehouse
            - --ingress-url-format=$(ingress-url-format)
          env:
            - name: ingress-url-format
              value: ""  # Optional depending on your ingress
          ports:
            - containerPort: 8080
              name: metrics